name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install axios

      - name: Run update script
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          set -e
          # Configure Git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions@github.com'
          
          # Execute the update script
          node update_readme.js
          
          # Check for changes and commit if any
          git diff --exit-code || (
            git add README.md &&
            git commit -m "Update README with most visited repositories" &&
            git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:main
          )
          
          # Echo message if no changes
          echo "No changes to commit"
